awk -F',' '{ 
    system("wget -O " $1 ".tmp https://my.pgp-hms.org" $3) 
    cmd = "file -b " $1 ".tmp";
    cmd | getline ftype;
    close(cmd);
    ext = ".txt";
    if (ftype ~ /gzip/) { ext = ".txt.gz" }
    else if (ftype ~ /Zip/) { ext = ".zip" }
    system("mv " $1 ".tmp " $1 ext);
    print "Downloaded: " $1 ext;
}' ../Harvard_PGP_data.csv

for f in *.zip; do
    unzip "$f" -d "${f%.zip}"
    folder="${f%.zip}"
    mv "$folder"/*.txt "./$folder.txt"
    rmdir "$folder"
done
rm *.zip
rm *.txt.gz

grep -rL -e '^<!DOCTYPE HTML>' -e '^# This data file generated by 23andMe' *.txt | xargs rm

for f in $(grep -l '^<!DOCTYPE HTML>' *.txt); do
    cmd=$(grep '<PRE id="wget-example">' $f | sed 's/<PRE id="wget-example">\$ //; s/<\/PRE>//; s/&#39;/'\''/g')
    mkdir -p "${f%.txt}_tmp"
    cd "${f%.txt}_tmp"
    eval $cmd
    cd ..
done

for f in $(ls *_tmp/*.txt.bz2); do
    bunzip2 $f
done
for f in $(ls *_tmp/*.zip); do
    prefix=$(echo $f | sed 's/_.*//')
    unzip $f -d "./${prefix}_tmp"
done
for f in $(ls *_tmp/*.txt); do
    prefix=$(echo $f | sed 's/_.*//')
    mv $f "$prefix.txt"
done
rm -r *_tmp

mkdir -p PGP_data
for file in "PGP_raw_data"/*.txt; do
    id=$(basename "$file" .txt)
    echo $id
    plink1.9 --23file "$file" "$id" "$id" 0 -9 0 0 \
             --make-bed \
             --out "PGP_data/$id"
done

ls "PGP_data"/*.bed | sed 's/.bed//g' > PGP_data.txt
plink1.9 --merge-list PGP_data.txt --make-bed --out PGP_data

mkdir -p PGP_filtered_data
while read filepath; do
    filename=$(basename "$filepath")
    plink1.9 --bfile "$filepath" --exclude PGP_data-merge.missnp --make-bed --out "PGP_filtered_data/$filename"
done < PGP_data.txt

ls PGP_filtered_data/*.bed | sed 's/.bed//g' > PGP_filtered_data.txt
plink1.9 --merge-list PGP_filtered_data.txt --make-bed --out PGP_filtered_data

